### ISSUE TITLE
[JOSS Review] Description of the package uses acronym

### ISSUE THREAD

**Issue by Sbozzolo** [a-renzini/pygwb#3]
[setup.py](https://github.com/a-renzini/pygwb/blob/763f55636d42055e56f4ea864de0f536a06da91f/setup.py#L27)  describes the package as `Lighweight python stochastic GWB analysis pipeline`. This description ends up in PyPI and other various places, so I would suggest spelling out what GWB means. 

Also, the `classifiers` is probably missing Python 3.11?

**Comment by kevinturbang** [comment]
This was addressed in the most recent MR. Thank you for flagging this.
